Add version to addresses files
ourzora/zora-1155-contracts pull request #141
Opened 2023-08-15 20:15 UTC by iainnash

2023-08-15 20:21 UTC, kulkarohan approved these changes

2023-08-15 20:34 UTC, oveddan commented
would be better as:
CONTRACT_1155_IMPL: {
   address: 0x....,
   version: "1.4.0"
}

this would make it easier to consume in the sdk

2023-08-15 20:35 UTC, oveddan requested changes
please see comment about formatting

2023-08-15 20:35 UTC, oveddan commented
can we also have the deployment scripts populating the values, instead of having to manually set them? manually setting seems precarious

2023-08-15 20:53 UTC, oveddan commented
can you verify that the script `node script/copy-deployed-contracts.mjs deploy` still works as expected?

2023-08-23 08:02 UTC, kolber commented on addresses/420.json
> +  "CONTRACT_1155_IMPL_VERSION": "1.4.0",
🙌

2023-08-23 15:57 UTC, oveddan approved these changes
please fix build then SGTM.  lets look at a better way to tag versions in the future

2023-09-12 15:20 UTC, merged